### ISSUE TITLE
How should I run Orca without mahimahi?

### ISSUE THREAD

**Issue by wen-zheng** [Soheil-ab/Orca#1]
I want to run Orca server and Orca client on two separate machines which are connected by the third one (router) and emulate different network environments on the router by linux tc and netem. How should I run Orca without mahimahi?

**Comment by wen-zheng** [comment]
I got it.

**Comment by wen-zheng** [comment]
And how should I incrementally update the current model in this scenario?

**Comment by Soheil-ab** [comment]
@wen-zheng,

Hi Wen-Zheng. 

Regarding running Orca without Mahimahi, 
you can use orca-server-mahimahi.cc file as the base and comment the part of code that brings up Mahimahi (and client) therein. Then simply execute server binary first (@ server side) and then client binary (@ client side). You can find the required inputs to the client and server codes in the corresponding c files. 

Regarding training Orca, 
You need to configure the json file and set the ip addresses of the machine that you use as the "Learner" and machines that you use as "Actors". In your case, you have only one machine as the actor which will be the server side. The client plays just as a receiver of traffic (and Ack generator) and it is not needed to be configured in a specific way.

Please let me know if you have more questions or need more help.

 (BTW, please mention me directly in your comments using \"\@\", otherwise I won't be notified! I saw your current comments randomly!)

**Comment by wen-zheng** [comment]
@Soheil-ab 
Thanks. 
I modified the orca-server-mahimahi.cc file as follows:
![image](https://user-images.githubusercontent.com/33896328/91716259-dbf98600-ebc1-11ea-9801-74cfdea974c1.png)
I comment the line 148 and 152~157 to disable local client and mahimahi, and I run the server by the command `bash ./orca-standalone-emulation.sh port` for utilizing the default settings and the trained model,
run the client by the command `sudo  ./rl-module/client server_ip flow_id server_port`.
Is right?  does this use a trained model? and the trained model is the same as the Sigcomm paper?
Thanks for your help!!

**Comment by Soheil-ab** [comment]
@wen-zheng,

You also need to comment the line 243: ==>     system(final_cmd);
If you don't change the default path to the trained model, server will use the trained model (the SIGCOMM paper). 

A few general notes: 
1- (Mainly) The \"json\" files are used to the configure the DRL module including the path to trained model, various DRL parameters, Actor/Learner IP addresses, etc. By changing the configuration files you can play with the parameters of the DRL block. 

2- And remember that if you wanna update the trained model, you need to take care of the catastrophic forgetting meaning if you train the system for a long time only over a certain scenario, you most likely will lose the currently trained model (plz check out the paper for more details).

Plz let me know if you have any more questions.

**Comment by wen-zheng** [comment]
@Soheil-ab

Thank you. I have succeeded.

**Comment by kefanchen** [comment]
@wen-zheng,
Hello, I also want to run orca on linux TC emulated link, could you please tell me what steps you have taken to achieve this?
Is it as follows?
1.comment line 148 and 152~157 243 in orca-server-mahimahi.cc
2. on server: bash ./orca-standalone-emulation.sh port
3. on client: sudo ./rl-module/client server_ip flow_id server_port 

 Thank you! Looking forward to your reply.
十分感谢，烦请不吝赐教。
