### ISSUE TITLE
cwnd control of Orca

### ISSUE THREAD

**Issue by Alan-JW** [Soheil-ab/Orca#6]
I would like to ask you a question: in order to reproduce the case of Figure 9: in your paper, and I found that the maximum value of cwnd in this process is up to 2147483648, could it be that target_ratio=1.1*orca_info is causing the cwnd to increase too aggressively?
Here are my [Orac cubic 24mbps-12mbps](https://docs.google.com/document/d/1DW-Sjk7hj-m2u7zLPXYJMLFUqEh8TxqFfJwUgoQAna0/edit#heading=h.swlmdy1ddbdj)
Thank you very much for your answer.

**Comment by Alan-JW** [comment]
@Soheil-ab

**Comment by Soheil-ab** [comment]
Hey @Alan-JW 

An important setting in your case which dramatically impacts the performance is the "no buffer" phrase mentioned in the first page of your results. Since you are using Mahimahi, that means **unlimited** buffer size. The very first impact of this setting is that there will be no packet drop in the network. Roughly speaking, that means "Cubic" will remain in slow-start phase! 
In Linux, the rule of thumb is that you are in slow-start phase when cwnd<ssthresh (Check out this: https://elixir.bootlin.com/linux/v4.13.1/source/include/net/tcp.h#L1113) (We also use this on line 445 of the orca-server-mahimahi.cc). The initial value of the ssthresh in Linux is the number that you have observed: 2147483648 (0x80000000)!

Putting all together, you see the increase of cwnd to the value of 2147483648, because the network doesn't drop a packet (unlimited buffer size) and system remains in the slow-start phase (The control won't hand over to Orca!). As I mentioned during the answer to your other question, Orca takes the control of the system only after the first slow-start phase is finished.

**Comment by Alan-JW** [comment]
@Soheil-ab 
Okay, I see, but from my follow-up tests, the increase of cwnd to the system default maximum only happens when the RTT is 50ms or more. At RTT equal to 10ms, 20ms, cwnd only increases to three digits and then exits the  slow-start.

**Comment by Soheil-ab** [comment]
Hey @Alan-JW 

As I mentioned, **"roughly speaking"**, no real packet drops in the network keeps the system in the slow-start phase. To be precise, there are other mechanisms involved therein. Detecting loss of a packet in TCP, as you may know, happens through the use of TCP timers. In particular, there is an RTO period before triggering a packet loss. The value of RTO depends on the value of a so called smoothed RTT though! Smoothed RTT is calculated by applying an EWMA filter to RTT... Making the story short, having larger RTTs makes the detection of loss less frequently in TCP. 

Second, the **current** slow-start tweak implemented in orca-server-mahimahi.cc happens **periodically** (independent of RTT of the system). That means for larger RTTs the number of multiplications to 1.1 will also increase (during slow-start). 

That is why by increasing RTT you see different behaviors during the slow-start phase.

**Comment by Alan-JW** [comment]
@Soheil-ab 
Okay, I see. Thank you very much for your answer.

**Comment by Soheil-ab** [comment]
You're welcome
