### ISSUE TITLE
Three Questions in model testing

### ISSUE THREAD

**Issue by Alan-JW** [Soheil-ab/Orca#8]
Hey , @Soheil-ab 

I found some of the following phenomena when using the model,

1.  In conducting the bandwidth burst（24mbps to 12mbps） test, I found that when rtt is large (rtt>100ms),tput will oscillate after the bandwidth burst decrease.

2.  In some experiments, such as bw=5mbps, 10mbps, 12mbps, tput will appear ‘tail-up’phenomenon.

3.  When training the model on the basis of the original model (Train trace：Bandwidth ：24mbps->12mbps),I found that the actor loss and critical loss continued to rise, and the results in the test trace(Bandwidth ：24mbps->12mbps) after training were not as good as the original model.

Here are my [concrete results](https://docs.google.com/document/d/1cF22JNMVrmCGFnJhOakBw9E1WzYHOHLvbSDj43xssdg/edit#heading=h.7mggrfw6ghrm)

I would like to ask you if you encountered any of the problems I mentioned above during your previous use or testing? If so, how did you solve these problems?

Thank you very much for your answer.

**Comment by Soheil-ab** [comment]
Hey @Alan-JW 

I will look into your results and come back to you in a few days. Meanwhile, regarding your 3rd question, 

3- Training the system on top of the current model might be a little bit tricky! 
I don't expect you to see good performance by only using one extra environment to train the system on top of the current model. I expect that you get better results by starting from the scratch and just train on your chosen environment. Why is that? There are multiple factors involved here. First, the current model is trained over more than 300 environments IN PARALLEL. That means we tried to not emphasize on any env during the training. So, if you wanna add a new environment to this list AFTER the training of the first model, you need to make sure that the system will not forget the previous model! That goes to the direction of continual learning! Second, you need to make sure that you give the system enough time during the training to really improve the model. Generally speaking, I suggest that you don't perform SEQUENTIAL training, b.c you always need to be careful about catastrophic forgetting issue.

**Comment by Alan-JW** [comment]
Hey @Soheil-ab 
Okay, as you mentioned that you used more than 300 environments in parallel to train the Orca model, could you please provide your training set? This might be useful when we retrain the model. Thank you very much.

**Comment by Soheil-ab** [comment]
Hey @Alan-JW 

Sorry for the delay (I was/am super-busy these days). Ok, let's see what we have here. 

1- Regarding step scenario with very large minRTTs:
Orca uses a recurrent structure (as discussed in section 3.1). The current size is 10. That means the latest 10 reported measurements/samples will be aggregated to form the current state of the system. On the other hand, Reports are only valid, when source has received valid Acks. That said, roughly speaking, a valid measurement happens, on average, every RTT.  

Now, let's see what happens when you increase the minRTT to very large values like 800ms. For very large minRTTs, the system requires a large time (e.g. with 800ms minRTT, that becomes a few seconds) for observing a meaningful recurrent input signal (~10RTTs). Besides, in the step scenario, we have a sudden queue build-up at around 15s which will lead to have even larger time window for receiving Acks and building meaningful recurrent input signals. Putting all together, a very large RTT, increases the time of the control loop and this can make the oscillations when network suddenly changes too much.  

2- Regarding a small ramp-up at the end of your evaluations on links with very low BW and large RTTs:
Orca is not sensitive to the time of evaluation (in this case finishing time)! So, what you see there likely happens because of Mahimahi and the order by which we kill the client, server, and mahimahi processes. You can also check out how we parse the output file to draw the graphs that you see (e.g. mm-thr script).

3- Regarding the training:
I encourage you to check out sections 3.5 and 4 to have a feeling about how the training phase is done. You can find the environments used in Table 2 (e.g. you can choose logish steps in every input direction to make the environments). 

BTW, to me, based on your shown output, the performance of Orca has been improved on the Step scenario after your training sessions. :-)
